name: wallgram
description: "A new Flutter project."

publish_to: "none"

version: 1.3.1+2

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.7
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^19.2.1
  flutter_offline: ^5.0.0
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  google_sign_in: ^6.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  mime: ^2.0.0
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5
  quickalert: ^1.1.0
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  supabase_flutter: ^2.9.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/wall.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - .env
