// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAogcKBYwsCbBH9SGBb68_jx4Wuy5lgFE',
    appId: '1:755663071671:web:efa841077132be7825e032',
    messagingSenderId: '755663071671',
    projectId: 'wallgram-4a6e0',
    authDomain: 'wallgram-4a6e0.firebaseapp.com',
    storageBucket: 'wallgram-4a6e0.firebasestorage.app',
    measurementId: 'G-FWJSGWB9ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9TLJ-3n8TPi2lhf-d0X2VJ7w8VQh9TVw',
    appId: '1:755663071671:android:5ffe24ca268309ff25e032',
    messagingSenderId: '755663071671',
    projectId: 'wallgram-4a6e0',
    storageBucket: 'wallgram-4a6e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB00xlIMdQKHR2orwiO9VKEBi5rlsrKHhg',
    appId: '1:755663071671:ios:d9f565de61c09a9d25e032',
    messagingSenderId: '755663071671',
    projectId: 'wallgram-4a6e0',
    storageBucket: 'wallgram-4a6e0.firebasestorage.app',
    iosBundleId: 'com.example.wallgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB00xlIMdQKHR2orwiO9VKEBi5rlsrKHhg',
    appId: '1:755663071671:ios:d9f565de61c09a9d25e032',
    messagingSenderId: '755663071671',
    projectId: 'wallgram-4a6e0',
    storageBucket: 'wallgram-4a6e0.firebasestorage.app',
    iosBundleId: 'com.example.wallgram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAogcKBYwsCbBH9SGBb68_jx4Wuy5lgFE',
    appId: '1:755663071671:web:6a411c0ff8f2016525e032',
    messagingSenderId: '755663071671',
    projectId: 'wallgram-4a6e0',
    authDomain: 'wallgram-4a6e0.firebaseapp.com',
    storageBucket: 'wallgram-4a6e0.firebasestorage.app',
    measurementId: 'G-Y0GLZWNJ8Y',
  );
}
